language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
- chmod a+x ./mvnw

install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.server=true -B -V 

script: ./mvnw verify

after_failure:
- find target/it -name server.log -exec echo {} \; -exec cat {} \;
