language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
- chmod a+x ./mvnw

script:
- ./mvnw clean install -DskipTests
- ./mvnw verify "-Dit.test=Retry*, Timeout*, CircuitBreaker*"
